### ISSUE TITLE
What is dummy_link for in adding_sensors ?

### ISSUE THREAD

**Issue by dogoepp** [resibots/hexapod_ros#5]
Hello,

In branch `adding_sensors`, the [first commit](https://github.com/resibots/hexapod_ros/commit/39c02840b9c420ff59d81bb0e3bc306193282a30) adds a link named "dummy_link". What is it for ?

@virgileTN

**Comment by costashatz** [comment]
> In branch adding_sensors, the first commit adds a link named "dummy_link". What is it for ?

This should be for fixing the hexapod (not allow it to move) to the world. We should remove it..
