### ISSUE TITLE
Settle the Xacro and URDF files

### ISSUE THREAD

**Issue by dogoepp** [resibots/hexapod_ros#6]
For now, the branch `adding_sensors` hosts modified models of the hexapods allowing to represent the sensors. However, we cannot merge this into master, since Pexod doesn't have these sensors.

Furthermore, the model for a leg should be updated for the new hexapod, since it differs from Pexod.

What do you think is the best approach to factor as much as possible of the hexapod's models ?

**Comment by costashatz** [comment]
> For now, the branch adding_sensors hosts modified models of the hexapods allowing to represent the sensors. However, we cannot merge this into master, since Pexod doesn't have these sensors.
> 
> Furthermore, the model for a leg should be updated for the new hexapod, since it differs from Pexod.
> 
> What do you think is the best approach to factor as much as possible of the hexapod's models ?

It is already as generic as it can be. we need to create several `robot.xacro` files (possibly with the name of each robot) and create different `leg.xacro` and `legs.xacro` files. I can make the changes once I have some time (most probably after my deadlines - 10-15 Sept).

**Comment by dogoepp** [comment]
> It is already as generic as it can be. we need to create several 
> |robot.xacro| files (possibly with the name of each robot) and create 
> different |leg.xacro| and |legs.xacro| files. I can make the changes 
> once I have some time (most probably after my deadlines - 10-15 Sept).

Thanks for your opinion. I'll see if I can get it right and make a pull 
request.

**Comment by dogoepp** [comment]
fixed by #11.
